### ISSUE TITLE
aaaaaa

### ISSUE THREAD

**Issue by Antlrr** [bittermc/bittermc.github.io#1]
Fuck help, how does GitHub work

**Comment by macimas** [comment]
# GitHub
From Wikipedia, the free encyclopedia.

GitHub, Inc. is a provider of Internet hosting for software development and version control using Git. It offers the distributed version control and source code management (SCM) functionality of Git, plus its own features. It provides access control and several collaboration features such as bug tracking, feature requests, task management, continuous integration and wikis for every project.[4] Headquartered in California, it has been a subsidiary of Microsoft since 2018.
